interface RichImageInterface @typeResolver(class: "Mygento\\Image\\Model\\Resolver\\RichImageInterfaceType") {
    width: Int!
    height: Int!
    default: ResponsiveRichImage!
    avif: ResponsiveRichImage!
    webp: ResponsiveRichImage!
    thumbnail: RichImageInterface
}

type ResponsiveRichImage {
    srcset: String!
    url: String!
    lqip: String
}

type RichMediaGallery implements RichImageInterface
{
}

type RichProductImage implements RichImageInterface
{
}

type RichImage implements RichImageInterface
{
}

type ProductImage {
    image: RichProductImage @resolver(class: "Mygento\\Image\\Model\\Resolver\\Product\\Gallery")
}

interface ProductInterface {
    image: RichProductImage @resolver(class: "Mygento\\Image\\Model\\Resolver\\Product\\Image")
    small_image: RichProductImage @resolver(class: "Mygento\\Image\\Model\\Resolver\\Product\\SmallImage")
    thumbnail: RichProductImage @resolver(class: "Mygento\\Image\\Model\\Resolver\\Product\\Thumbnail")
}